### ISSUE TITLE
Assignment1 ready for grading

### ISSUE THREAD

**Issue by Li-Aijing** [SES-5215-F2020/aijingli-quant#1]
Hi there I updated the rmd and https files for assignment 1. Looking forward to your comments!

**Comment by c-voulgaris** [comment]
Note: You should assign issues to me and to Sara Tepfer - not to Catherine. Catherine won't be doing any grading.

Great job!

**Comments on code/details:**
Lines 12-16: You don't need to include these lines. Your code will run fine without them. On the other hand, they way you've included them (in a separate section, with a comment explaining what they're for) is really clear.

Line 28: You are including Hispanic/Latino as a category, so the description of this variable is confusing/misleading.

Line 37: As far as I can tell, you don't use this variable, so you can delete this line.

Line 46: I think this is one of three variables that describe a subset of people who are multi-racial; double-check that this is what you want. This won't effect your results much, I don't think, because I doubt there are tracts that are majority multi-racial.

Line 73/96: Consider why these values are NA or NaN. NA indicates a missing value and NaN usually means you've divided by zero (so you'd get this for percent of workers riding public transit if there are no workers in that tract). So instead of saying "I deleted lines with NAs or NaNs" you could explain it more clearly by saying, "I excluded tracts with missing values for travel time to work or median income, as well as tracts with no workers." It's possible that all three things are from tracts with no workers. If you can confirm this, you can simplify your explanation further by saying, "I excluded tracts with no workers."

**General comment:**
It's obvious from your code that your unit of analysis is the census tract, and I can see that you have 193 tracts in your dataset, but I'd like you to make both comments explicitly.
